apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-hello
  labels:
    app: echo-hello
spec:
  selector:
    matchLabels:
        app: echo-hello
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echo-hello
    spec:
      containers:
        - name: echo-hello
          image: 328183994804.dkr.ecr.us-east-1.amazonaws.com/echo-hello:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always