## Build
FROM golang:1.19-buster AS build

WORKDIR /app

COPY echo/go.mod ./
COPY echo/go.sum ./
RUN go mod download

COPY echo/*.go ./

RUN go build -o /echo-hello

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /echo-hello /echo-hello

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/echo-hello"]